title: This is davidcosama's blog
author: davidcosama
email: davidcosama@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  This will be place where I'd like to share my new code repos and ideas related to code.

# social links
twitter_username: pending # DO NOT include the @ character, or else the build will fail!
github_username:  davidcosama # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
